services:
  postgresql:
    container_name: postgres
    image: postgres:14.7
    volumes:
      - './pgdata/data:/var/lib/postgresql/data'
      #- '~/Workspace/kafka/yaml/postgres/script/'
      - './scripts/postgres:/docker-entrypoint-initdb.d/'

    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USERNAME=postgres
      - POSTGRES_DATABASE=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
      - TZ=Asia/Shanghai
      - PGDATA=/var/lib/postgresql/data/pgdata
    networks:
      - pgnetwork

volumes:
  postgres_data:
    driver: local

networks:
  pgnetwork:
    driver: bridge



