services:
  zookeeper:
    container_name: zookeeper
    image: docker.io/bitnami/zookeeper:3.8.1
    ports:
      - "2181:2181"
    volumes:
      - zookeeper_data:/bitnami
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes            # 允许匿名访问
      - ZOO_AUTH_ENABLED=no                  # 启用身份验证
      # - ZOO_AUTH_TYPE=sasl                 # 使用 SASL 身份验证
      # - ZOO_SASL_CLIENT=true               # 启用客户端 SASL
      # - ZOO_SASL_SERVER=true               # 启用服务器 SASL
      # - ZOO_SASL_CLIENT_USERNAME=sample    # 客户端用户名
      # - ZOO_SASL_CLIENT_PASSWORD=kafka     # 客户端密码
    networks:
      - kafka_network

  kafka:
    container_name: kafka
    image: docker.io/bitnami/kafka:3.5.2
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://192.168.31.200:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes       # 允许明文监听器（可选）
      # - KAFKA_SECURITY_PROTOCOL=SASL_PLAINTEXT # 使用 SASL 安全协议
      # - KAFKA_SASL_MECHANISM=PLAIN         # 使用 PLAIN SASL 机制
      # - KAFKA_SASL_JAAS_CONFIG=org.apache.kafka.common.security.plain.PlainLoginModule required username=sample password=kafka; # JAAS 配置
    networks:
      - kafka_network

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local

networks:
  kafka_network:
    driver: bridge